name: heatmap_calendar_plus
description: A customizable heatmap-style calendar widget for Flutter. Fork of flutter_heatmap_calendar, actively maintained with updates, bug fixes, and new features.
version: 1.0.0
repository: https://github.com/JherysVargas/heatmap_calendar_plus
homepage: https://github.com/JherysVargas/heatmap_calendar_plus
issue_tracker: https://github.com/JherysVargas/heatmap_calendar_plus/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
